### PR TITLE
fix ConcurrentModificationException in ServiceExportsRepository

### PR DESCRIPTION
**Pull request by ponziani**
When using Aries RSA we regularly experience a ConcurrentModificationException in ServiceExportsRepository. This PR contains a very simple and straightforward fix for that.

### CODE REVIEW

**Comment by timothyjward** [comment]
Looking at the map access there is some very inconsistent synchronisation here. I’m not sure that this fix will actually eliminate the issue.

**Comment by ponziani** [comment]
Hi @timothyjward ,

Thanks for your quick response. I'm absolutely no expert on the matter, but from reading [this SO answer](https://stackoverflow.com/a/16180833/4937772) I learnt that the current code (using exportsMap.get(sref) in a for-loop) is asking for a ConcurrentModificationException.

> In access-ordered linked hash maps, merely querying the map with get is a structural modification.

Maybe other improvements are possible as well, but for us this little improvement managed to get rid of the stacktrace.

**Comment by ponziani** [comment]
Made a few extra improvements. All our issues are fixed now, the new code has been running for quite a while already.

**Comment by amichair** [comment]
I've opened and fixed https://issues.apache.org/jira/browse/ARIES-2130 based on this PR.

Note that the link and quote above about LinkedHashMap specifically refer to access-ordered linked hash maps, in which a get operation can modify it. However, the default for LinkedHashMap when using the no-args constructor, as in our case, is to use insertion order rather than access order, so there shouldn't be any modifications caused by the get operations afaik.

As for replacing keySet iteration followed by get with a single values iteration, I applied that as well though it has nothing to do with concurrency, just for readability and performance. In general, one should iterate over the keySet when only keys are needed, iterate over values when only values are needed, and iterate over entrySet when both are needed as a pair.

Finally, for the concurrency fix, there are a couple of methods that were accessing the exportsMap (and the lists within it that also need to be accessed concurrently) that weren't synchronized, so I added it as in your fix, which I think should solve the problem. However, the commit above also synchronized two of the ExportRegistrationHolder methods that have nothing to do with this map, and without a stack trace or additional info or explanation it's hard to tell if there was indeed another problem encountered there or this was just added 'just in case' but it is unclear why. I'm reluctant to add them since unnecessary synchronization can also lead to deadlocks, so they should be used with caution. If you have additional info on this please open a separate issue with the details.

**Comment by ponziani** [comment]
Thanks for the merge and the explanations!

**Pull request closed without merging**
