### PR TITLE
Little refactorings and code cleanup

### PR DESCRIPTION
**Pull request by amichair**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/3/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='Aries-rsa-pr/org.apache.aries.rsa.itests:org.apache.aries.rsa.itests.felix' /><a href='https://builds.apache.org/job/Aries-rsa-pr/3/org.apache.aries.rsa.itests$org.apache.aries.rsa.itests.felix/testReport'>Aries-rsa-pr/org.apache.aries.rsa.itests:org.apache.aries.rsa.itests.felix</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/Aries-rsa-pr/3/org.apache.aries.rsa.itests$org.apache.aries.rsa.itests.felix/testReport/org.apache.aries.rsa.itests.felix.fastbin/TestFastbinRoundTrip/testCall/'><strong>org.apache.aries.rsa.itests.felix.fastbin.TestFastbinRoundTrip.testCall</strong></a></li></ul>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/4/

**Comment by amichair** [comment]
The test failure above is some sort of race condition unrelated to this code change, I'll open a separate JIRA for it.

**Comment by cschneider** [comment]
The spurious fail of TestFastbinRoundTrip is well known. Would be great if you could solve the issue. I digged into it already but was not able to find the cause.

**Comment by cschneider** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/5/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='Aries-rsa-pr/org.apache.aries.rsa.itests:org.apache.aries.rsa.itests.felix' /><a href='https://builds.apache.org/job/Aries-rsa-pr/5/org.apache.aries.rsa.itests$org.apache.aries.rsa.itests.felix/testReport'>Aries-rsa-pr/org.apache.aries.rsa.itests:org.apache.aries.rsa.itests.felix</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/Aries-rsa-pr/5/org.apache.aries.rsa.itests$org.apache.aries.rsa.itests.felix/testReport/org.apache.aries.rsa.itests.felix.fastbin/TestFastbinRoundTrip/testCall/'><strong>org.apache.aries.rsa.itests.felix.fastbin.TestFastbinRoundTrip.testCall</strong></a></li></ul>

**Comment by cschneider** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/6/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='Aries-rsa-pr/org.apache.aries.rsa.itests:org.apache.aries.rsa.itests.felix' /><a href='https://builds.apache.org/job/Aries-rsa-pr/6/org.apache.aries.rsa.itests$org.apache.aries.rsa.itests.felix/testReport'>Aries-rsa-pr/org.apache.aries.rsa.itests:org.apache.aries.rsa.itests.felix</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/Aries-rsa-pr/6/org.apache.aries.rsa.itests$org.apache.aries.rsa.itests.felix/testReport/org.apache.aries.rsa.itests.felix.fastbin/TestFastbinRoundTrip/testCall/'><strong>org.apache.aries.rsa.itests.felix.fastbin.TestFastbinRoundTrip.testCall</strong></a></li></ul>

**Comment by cschneider** [comment]
Locally the build worked. So I will merge this pr.

**Pull request merged**
