### PR TITLE
Various Fixes

### PR DESCRIPTION
**Pull request by amichair**
Here are a bunch of fixes for various issues and some general cleanup. I can split it up into separate PRs of your choosing if it helps.

At least locally, the first fastbin activator fix significantly reduced the number of TestFastbinRoundTrip failures - I thought it solved it, but then saw the failure one more time out of tens of test runs, whereas before the fix it failed nearly always. The second fastbin activator fix might be related and help cover the remaining race condition, but can't tell for sure until we see the failure again or don't. In any case I think it's correct, whereas the previous atomic boolean use, at least to me, didn't seem to do what someone thought it's supposed to do :-)

If I misunderstood anything or anything requires revision, let me know.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/7/

**Comment by amichair** [comment]
Yay, Jenkins like it!

Maybe have it run a few more times to see if we get the fastbin failure again?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/8/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/9/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-rsa-pr/10/

**Comment by amichair** [comment]
Added a couple dependency updates.

Now 4/4 Jenkins runs are successful, so looking good. btw what I've seen matches ARIES-1835 more than it does ARIES-1836.

**Comment by cschneider** [comment]
Yes. Would be great if you could split it up. All together it is a bit much to validate... and more PR look good in the stats :-)

**Comment by amichair** [comment]
ok, opened separate PRs. Some builds failed due to the fastbin test, if u merge that fix first I can rebase the others and retest (assuming it fixes it :-) )

**Pull request closed without merging**
