### PR TITLE
[ARIES-1573] Integration tests

### PR DESCRIPTION
**Pull request by dpishchukhin**

### CODE REVIEW

**Comment by dpishchukhin** [comment]
by some reason I cannot run tests with forked container. With native everything is fine.

**Comment by cschneider** [comment]
I merged your change. The build runs fine for me. Can you recheck with current master?

I see build failures in jenkins too (already before your change). If you have any chance to look into this https://builds.apache.org/me/my-views/view/My/job/Aries-rsa%20master/ .
I supect it might be the local repo location.

**Comment by dpishchukhin** [comment]
problems were related to pax exam forked container. you resolved it already. you can close this PR

**Comment by cschneider** [comment]
What is the status of this PR? The tests work for me and also on the jenkins server. 
Do you still have problems with the itests?

**Comment by dpishchukhin** [comment]
No. I close it

**Pull request closed without merging**
